
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 20151114010668
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        btngGrupo.add(jrbAndar);
        btngGrupo.add(jrbAbastecer);
        btngGrupo.add(jrbConsultar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngGrupo = new javax.swing.ButtonGroup();
        jrbAndar = new javax.swing.JRadioButton();
        jrbAbastecer = new javax.swing.JRadioButton();
        jrbConsultar = new javax.swing.JRadioButton();
        jcbAuto = new javax.swing.JComboBox();
        jtfExecutar = new javax.swing.JTextField();
        jbtnExecutar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jrbAndar.setText("Andar");

        jrbAbastecer.setText("Abastecer");

        jrbConsultar.setText("Consultar Tanque");

        jcbAuto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Carro", "Moto" }));
        jcbAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAutoActionPerformed(evt);
            }
        });

        jbtnExecutar.setText("Executar");
        jbtnExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExecutarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jcbAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbConsultar)
                    .addComponent(jrbAbastecer)
                    .addComponent(jrbAndar))
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jtfExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jbtnExecutar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbAndar)
                    .addComponent(jcbAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jrbAbastecer)
                .addGap(18, 18, 18)
                .addComponent(jrbConsultar)
                .addGap(40, 40, 40)
                .addComponent(jtfExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnExecutar)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAutoActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jcbAutoActionPerformed

    private void jbtnExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExecutarActionPerformed
        // TODO add your handling code here:
        String h;
        int helo;
        String itemSelecionado = jcbAuto.getSelectedItem().toString();
        
        if(itemSelecionado.equals("Carro")){
            Carro carro = new Carro();
            
            if(jrbAndar.isSelected()){
                h = jtfExecutar.getText();
                helo = Integer.parseInt(h);
                carro.andar(helo);
            }else if(jrbAbastecer.isSelected()){
                h = jtfExecutar.getText();
                helo = Integer.parseInt(h);
                carro.abastecer(helo);
                
            }
        }else{
            
        }
        
        
    }//GEN-LAST:event_jbtnExecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngGrupo;
    private javax.swing.JButton jbtnExecutar;
    private javax.swing.JComboBox jcbAuto;
    private javax.swing.JRadioButton jrbAbastecer;
    private javax.swing.JRadioButton jrbAndar;
    private javax.swing.JRadioButton jrbConsultar;
    private javax.swing.JTextField jtfExecutar;
    // End of variables declaration//GEN-END:variables
}
