/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 20151114010668
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfSalario = new javax.swing.JTextField();
        jbtnCalcular = new javax.swing.JButton();
        jrbDiretor = new javax.swing.JRadioButton();
        jrbProfessor = new javax.swing.JRadioButton();
        jrbEstagiario = new javax.swing.JRadioButton();
        jlCifrao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnCalcular.setText("OK");
        jbtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalcularActionPerformed(evt);
            }
        });

        jrbDiretor.setText("Diretor");

        jrbProfessor.setText("Professor");

        jrbEstagiario.setText("Estagiario");
        jrbEstagiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEstagiarioActionPerformed(evt);
            }
        });

        jlCifrao.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbDiretor)
                            .addComponent(jrbProfessor)
                            .addComponent(jrbEstagiario)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jlCifrao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jbtnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCifrao))
                .addGap(35, 35, 35)
                .addComponent(jrbDiretor)
                .addGap(18, 18, 18)
                .addComponent(jrbProfessor)
                .addGap(18, 18, 18)
                .addComponent(jrbEstagiario)
                .addGap(34, 34, 34)
                .addComponent(jbtnCalcular)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbEstagiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEstagiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbEstagiarioActionPerformed

    private void jbtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalcularActionPerformed
        // TODO add your handling code here:
        Diretor d1 = new Diretor();
        Professor p1 = new Professor();
        Estagiario e1 = new Estagiario();
        
        double salario;
        String salario2;
        
        if(jrbDiretor.isSelected()){
            salario = d1.calcularSalario();
 
            salario2 = String.valueOf(salario);
            jtfSalario.setText(salario2);
            jrbDiretor.setSelected(false);
            
        }else if(jrbProfessor.isSelected()){
            salario = p1.calcularSalario();
            
            salario2 = String.valueOf(salario);
            jtfSalario.setText(salario2);
            jrbProfessor.setSelected(false);
            
        }else if(jrbEstagiario.isSelected()){
            salario = e1.calcularSalario();
            
            salario2 = String.valueOf(salario);
            
            jtfSalario.setText(salario2);
            
            jrbEstagiario.setSelected(false);
            
        }
        
    }//GEN-LAST:event_jbtnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCalcular;
    private javax.swing.JLabel jlCifrao;
    private javax.swing.JRadioButton jrbDiretor;
    private javax.swing.JRadioButton jrbEstagiario;
    private javax.swing.JRadioButton jrbProfessor;
    private javax.swing.JTextField jtfSalario;
    // End of variables declaration//GEN-END:variables
}
